import { index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
const stamp={createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()};
export const users=sqliteTable('users',{id:text('id').primaryKey(),externalId:text('external_id'),firstName:text('first_name').notNull(),lastName:text('last_name').notNull(),displayName:text('display_name').notNull(),email:text('email'),role:text('role').notNull(),active:integer('active',{mode:'boolean'}).notNull().default(true),...stamp});
export const advisorStudents=sqliteTable('advisor_students',{id:text('id').primaryKey(),advisorId:text('advisor_id').notNull(),studentId:text('student_id').notNull(),active:integer('active',{mode:'boolean'}).notNull().default(true),...stamp},t=>[uniqueIndex('uq_advisor_student').on(t.advisorId,t.studentId)]);
export const recurrenceRules=sqliteTable('recurrence_rules',{id:text('id').primaryKey(),frequency:text('frequency').notNull(),interval:integer('interval').notNull().default(1),daysOfWeek:text('days_of_week'),dayOfMonth:integer('day_of_month'),startAt:text('start_at').notNull(),endAt:text('end_at'),nextOccurrenceAt:text('next_occurrence_at').notNull(),active:integer('active',{mode:'boolean'}).notNull().default(true),...stamp});
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),ownerUserId:text('owner_user_id').notNull(),assignedByUserId:text('assigned_by_user_id'),title:text('title').notNull(),description:text('description'),status:text('status').notNull().default('TODO'),priority:text('priority').notNull().default('NORMAL'),dueAt:text('due_at'),scheduledStartAt:text('scheduled_start_at'),scheduledEndAt:text('scheduled_end_at'),completedAt:text('completed_at'),estimatedMinutes:integer('estimated_minutes'),sourceType:text('source_type').notNull(),sourceExternalId:text('source_external_id'),sourceMetadata:text('source_metadata'),recurrenceRuleId:text('recurrence_rule_id'),parentTaskId:text('parent_task_id'),sortOrder:integer('sort_order').notNull().default(0),deletedAt:text('deleted_at'),...stamp},t=>[index('idx_tasks_owner_status').on(t.ownerUserId,t.status),index('idx_tasks_due').on(t.dueAt),uniqueIndex('uq_tasks_source').on(t.sourceType,t.sourceExternalId)]);
export const taskActivities=sqliteTable('task_activities',{id:text('id').primaryKey(),taskId:text('task_id').notNull(),actorUserId:text('actor_user_id').notNull(),eventType:text('event_type').notNull(),occurredAt:text('occurred_at').notNull(),metadata:text('metadata')},t=>[index('idx_activity_task').on(t.taskId)]);
export const calendarEvents=sqliteTable('calendar_events',{id:text('id').primaryKey(),userId:text('user_id').notNull(),title:text('title').notNull(),startAt:text('start_at').notNull(),endAt:text('end_at').notNull(),allDay:integer('all_day',{mode:'boolean'}).notNull().default(false),sourceType:text('source_type').notNull(),sourceExternalId:text('source_external_id'),location:text('location'),rawMetadata:text('raw_metadata'),lastSyncedAt:text('last_synced_at'),...stamp},t=>[uniqueIndex('uq_events_source').on(t.sourceType,t.sourceExternalId),index('idx_events_user_start').on(t.userId,t.startAt)]);
export const syncRuns=sqliteTable('sync_runs',{id:text('id').primaryKey(),provider:text('provider').notNull(),userId:text('user_id').notNull(),startedAt:text('started_at').notNull(),completedAt:text('completed_at'),status:text('status').notNull(),itemsCreated:integer('items_created').notNull().default(0),itemsUpdated:integer('items_updated').notNull().default(0),itemsDeleted:integer('items_deleted').notNull().default(0),errorCode:text('error_code'),errorMessage:text('error_message')});
